apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config
  labels:
    type: local
spec:
  storageClassName: config
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt"
  nodeAffinity:
    required: 
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data
  labels:
    type: local
spec:
  storageClassName: consul-data
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-scripts
  labels:
    type: local
spec:
  storageClassName: scripts
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  local:
    path: "/var"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In 
          values:
          - localhost
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: edgex-core-consul
  name: consul-config
spec:
  storageClassName: config
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: edgex-core-consul
  name: consul-data
spec:
  storageClassName: consul-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: edgex-core-consul
  name: consul-scripts
spec:
  storageClassName: scripts
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: edgex-redis
  name: db-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi